// <auto-generated />
using System;
using DomesticManagement.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DomesticManagement.Database.Migrations
{
    [DbContext(typeof(DomesticManagementContext))]
    [Migration("20190420224522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomesticManagement.Database.Entities.DomesticResponsibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<Guid>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("ResponsibilityDescription");

                    b.Property<string>("ResponsibilityName");

                    b.HasKey("Id");

                    b.ToTable("DomesticResponsibilities");
                });

            modelBuilder.Entity("DomesticManagement.Database.Entities.DomesticResponsibilityOccurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<Guid>("DomesticResponsibilityId");

                    b.Property<Guid>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Note");

                    b.Property<DateTime>("OccuranceDateTime");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DomesticResponsibilityId");

                    b.HasIndex("UserId");

                    b.ToTable("DomesticResponsibilityOccurances");
                });

            modelBuilder.Entity("DomesticManagement.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<Guid>("CreatedBy");

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<Guid>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DomesticManagement.Database.Entities.DomesticResponsibilityOccurance", b =>
                {
                    b.HasOne("DomesticManagement.Database.Entities.DomesticResponsibility", "DomesticResponsibility")
                        .WithMany("DomesticResponsibilityOccurances")
                        .HasForeignKey("DomesticResponsibilityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DomesticManagement.Database.Entities.User", "User")
                        .WithMany("DomesticResponsibilityOccurances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
